### ISSUE TITLE
How to use the trained model?

### ISSUE THREAD

**Issue by nissansz** [twelfth-star/universal-font-recognition#2]

**Comment by twelfth-star** [comment]
If the trained CNN model is saved as  `../data/models/cnn_model.torch`, then you can use the following code
```python
import torch

cnn_net = torch.load('../data/models/cnn_model.torch')

img = Image.open(img_path)
img = img.copy().convert("L")

label = cnn_net(img)
```
The `label` will be the ID of the font.

**Comment by nissansz** [comment]
Do you have pre-trained model?
How to use onnx version for such model?

I tried https://github.com/HemingwayLee/deepfont-implement, and the result seems not correct for Japanese fonts.

**Comment by twelfth-star** [comment]
I have trained a toy model for Japanese fonts months ago. You can download the model [here](https://www.kaggle.com/datasets/hnthnt/jp-5-font-recognition-model). It can only recognize the following five fonts. You can download the fonts [here](https://www.kaggle.com/datasets/hnthnt/jp-5-font-dataset).
* GenEiAntiqueNv5-M.ttf
* GenEiKoburiMin6-R.ttf
* GenEiLateMinN_v2.ttf
* GenEiMGothic2-Bold.ttf
* GenEiMGothic2-Regular.ttf

I have refactored my code and I am currently trying to train a larger model which can recognize 169 Japanese fonts. I may release it soon.

**Comment by nissansz** [comment]
Good. Will wait for your large model to test. 
Ms gothic etc.

**Comment by nissansz** [comment]
import torch

# cnn_net = torch.load('../data/models/cnn_model.torch')
from PIL import Image

cnn_net = torch.load(r'L:/font/cnn_model.torch')

# img = Image.open(img_path)
img = Image.open(r'F:/24.png')
img = img.copy().convert("L")

label = cnn_net(img)
print(label)


报错===========================================

D:\Python3.8.8\python.exe F:/pycharm2020.2/universal-font-recognition-main/eval.py
Traceback (most recent call last):
  File "F:/pycharm2020.2/universal-font-recognition-main/eval.py", line 12, in <module>
    label = cnn_net(img)
  File "D:\Python3.8.8\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\pycharm2020.2\universal-font-recognition-main\utils\CNN.py", line 48, in forward
    X = self.Cu(X)
  File "D:\Python3.8.8\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Python3.8.8\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "D:\Python3.8.8\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Python3.8.8\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\Python3.8.8\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d() received an invalid combination of arguments - got (Image, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!Image!, !Parameter!, !Parameter!, !tuple!, !tuple!, !tuple!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!Image!, !Parameter!, !Parameter!, !tuple!, !tuple!, !tuple!, int)


Process finished with exit code 1
